### ISSUE TITLE
Input of the test case provided may have wrong MTO at sea level used for propulsion model + Take off dist constraint?

### ISSUE THREAD

**Issue by jpruscio** [fast-aircraft-design/FAST-OAD#104]
Maximum thrust for one engine at sea level (MTO) in the test case provided may be wrong.

MTO provided = 70 kN

MTO for CFM56 (A320 engine) = goes from 82 kN to 151 kN

I realized that due to the fact that the thrust rate for Ceras is 0.73, whereas for the MDA output analysis is 1.17, so we are short in engine. 
And also, some other parameters discrepancies between the MDA output and the Ceras as SFC that may come from this wrong MTO input. 
On the other hand, I also ran an optimization of the overall mission fuel consumption with the cruise altitude variation (design variable) and I obtained a cruise alt near 9000 ft and a fuel consumption of 2000 kg less than Ceras, so an aircraft that flies much lower and consumes near 12% less fuel, this led to ask if there is take off distance constraint, because such aircraft with smaller engines maybe possible of cruising much efficient than Ceras, but not able to take off at a coherent distance, so not a practical case.
To finish, I set up the MTO at 120kN instead of the 70kN provided in order to meet the 0.73 thrust rate result in the MDA run, so, to have the same thrust rate than Ceras, and in this way the parameters discrepancies observed before (I mean with the 70kN case provided) disappear, meaning that I obtained the same SFC between this case (the 120kN) and CeRAS xml. Then, I also ran again the same optimization of overall mission fuel consumption with the cruise alt in this new case (120kN of MTO) and I obtained pretty accurate values when comparing with Ceras, I mean an optimized cruise alt of 36000 feet (3% error), and the same fuel consumption for the entire mission (less than 1%).

**Comment by christophe-david** [comment]
Example in notebooks have been changed, so this issue does not apply anymore.
