### ISSUE TITLE
User capability to choose Cg margin

### ISSUE THREAD

**Issue by vinx012** [fast-aircraft-design/FAST-OAD#190]
The parameter "settings:weight:aircraft:CG:aft:MAC_position:margin" added as input in the "ComputeMaxCGratio" class could be added in the data.xml so that it could be easily changed. Useful when trying to reproduce an existing aircraft for which the cg operating range is known

**Comment by christophe-david** [comment]
Actually, it **should really be** in the input XML file. 
The rule is that any input OpenMDAO variable that is not fed by a matching output has to be in the generated input file.

Beware that the variable name begins by `settings:`, so you have to look in the `<settings>` node of the XML tree, unlike most variables that are in the `<data>` node.

To be complete, unlike most `data` variables, `settings` variables generally have a default value, so they are not required in the input file. Thus you can run a computation without having this variable in your input file.
But again, if you rely on the input generation command, it should be in the generated file. If it is not, please provide your configuration file and the generated input file.

**Comment by vinx012** [comment]
You're right it already is in the input file. However, I didnt't have it into the initial "aircraft_name.xml" file and I didn't think that it would have worked just adding manually the parameter in the "aircraft_name.xml". I did now and it works. Thanks
