### ISSUE TITLE
Error in test_openmdao_engine: FlightPhase.IDLE not encountered

### ISSUE THREAD

**Issue by areysset** [fast-aircraft-design/FAST-OAD#222]
See attached file
![FlightPhase_error](https://user-images.githubusercontent.com/46439339/93768251-665d6480-fc19-11ea-81f4-279f393050d0.png)

**Comment by christophe-david** [comment]
`IDLE` is part of `EngineSetting` enum class, not `FlightPhase`, and I do not see any `FlightPhase.IDLE` in FAST-OAD code, especially in `test_openmdao.py`.

**Comment by areysset** [comment]
Sorry, I used old test_openmdao model!
