### ISSUE TITLE
Add Mach target to Speed_change segment

### ISSUE THREAD

**Issue by vinx012** [fast-aircraft-design/FAST-OAD#228]
Hello,

Is it possible to add the mach target in the speed change segment as done below in the legacy version of fast?

    def _get_distance_to_target(self, flight_points: List[FlightPoint]) -> bool:
        if self.target.true_airspeed:
            return self.target.true_airspeed - flight_points[-1].true_airspeed
        elif self.target.equivalent_airspeed:
            return self.target.equivalent_airspeed - flight_points[-1].equivalent_airspeed
        **_elif self.target.mach:
            return self.target.mach - flight_points[-1].mach_**

Thanks,
Vincenzo

**Comment by christophe-david** [comment]
Indeed. Even the class docstring tells it should already be like that 😅
