### ISSUE TITLE
Can we upgrade atmosphere function with better get_equivalent_airspeed/get_true_airspeed functions?

### ISSUE THREAD

**Issue by areysset** [fast-aircraft-design/FAST-OAD#265]
Proposal:
[atmosphere.txt](https://github.com/fast-aircraft-design/FAST-OAD/files/5926899/atmosphere.txt)

Needed for CS23: we are currently patching the virtual environment!

**Comment by christophe-david** [comment]
Please propose a PR with proper unit tests and write a clear rationale with it.
