### ISSUE TITLE
404 error when doing api.write_n2() in Jupyter notebook 

### ISSUE THREAD

**Issue by christophe-david** [fast-aircraft-design/FAST-OAD#280]
OpenMDAO 3.7 introduces nice rendering of OpenMDAO views in Jupyter notebooks, but it collides with some features of FAST-OAD.
In particular, api.write_n2() shows a big frame with the "404: not found" message.

**Comment by ScottDelbecq** [comment]
The issue appears when an absolute path for the n2 file is provided to `om.n2()` which executes `IFrame(src=outfile, width=1000, height=1000)` which seems to generate the observed bug if called from a package and not a notebook cell. This does not happen if a relative path is provided.

Here are some lines of code to reproduce the bug in a notebook cell:

```python
import os.path as pth
import openmdao.api as om
from openmdao.test_suite.scripts.circuit_analysis import Resistor, Diode, Node

class Circuit(om.Group):

    def setup(self):
        self.add_subsystem('n1', Node(n_in=1, n_out=2), promotes_inputs=[('I_in:0', 'I_in')])
        self.add_subsystem('n2', Node())  # leaving defaults

        self.add_subsystem('R1', Resistor(R=100.), promotes_inputs=[('V_out', 'Vg')])
        self.add_subsystem('R2', Resistor(R=10000.))
        self.add_subsystem('D1', Diode(), promotes_inputs=[('V_out', 'Vg')])

        self.connect('n1.V', ['R1.V_in', 'R2.V_in'])
        self.connect('R1.I', 'n1.I_out:0')
        self.connect('R2.I', 'n1.I_out:1')

        self.connect('n2.V', ['R2.V_out', 'D1.V_in'])
        self.connect('R2.I', 'n2.I_in:0')
        # self.connect('D1.I', 'n2.I_out:0') # commented out so there is an unconnected input
                                             # example for docs for the N2 diagram

        self.nonlinear_solver = om.NewtonSolver(solve_subsystems=False)
        self.nonlinear_solver.options['iprint'] = 2
        self.nonlinear_solver.options['maxiter'] = 20
        self.linear_solver = om.DirectSolver()

p = om.Problem()
model = p.model

model.set_input_defaults('ground.V', 0., units='V')
model.set_input_defaults('source.I', 0.1, units='A')
model.add_subsystem('circuit', Circuit(),
                    promotes_inputs=[('Vg', 'ground.V'), ('I_in', 'source.I')])

model.add_design_var('ground.V')
model.add_design_var('source.I')
model.add_objective('circuit.D1.I')

p.setup()
p.check_config(checks=['unconnected_inputs'], out_file=None)

# set some initial guesses
p['circuit.n1.V'] = 10.
p['circuit.n2.V'] = 1.

p.run_model()

N2_FILE_PATH = "n2.html"

# Comment this next line to remove the bug
N2_FILE_PATH = pth.abspath(N2_FILE_PATH)
n2 = om.n2(p, outfile=N2_FILE_PATH, show_browser=False)
```

`api.write_n2()` in all cases transforms the file path into an absolute path. Do we really need to use an absolute path? 
Nevertheless, if we use the rendering of the n2 achieved by `om.n2()` we do not control the size of the IFrame because of this line:
```python
display(IFrame(src=outfile, width=1000, height=1000))
```

We could probably suggest to the developpers to use this configuration which uses the full screen width:
```python
display(IFrame(src=outfile, width="100%", height=700))
```

**Comment by christophe-david** [comment]
Great!
Actually, you show that it is an OpenMDAO bug. `om.n2()` accepts that `outfile` is an absolute path because it creates the html file. It just fails at displaying it in the notebook.

Then I suggest you raise an issue for OpenMDAO with this example. 
And I agree, you may also suggest to use all the available width (or to provide more control on the display in notebook).

As a workaround, yes, maybe we could stop making the path absolute.
Also, I see that by default, we write the `n2.html` file in the same folder as the FAST-OAD configuration file. If we have an absolute path for the configuration file, we will get an error anyway.
To have a real workaround, we should do as OpenMDAO and write the `n2.html` in working directory, wherever the configuration file would be. Maybe it would be better, because more expectable.
