### ISSUE TITLE
Problem using non-empty init file with custom made models: registering not working

### ISSUE THREAD

**Issue by areysset** [fast-aircraft-design/FAST-OAD#325]
Using a library of custom made models with __init__.py declaring internal classes i.e. (in geometry module):
from .geometry_fuselage import GeometryFixedFuselage
from .geometry_htp_distance import GeometryFixedTailDistance

Where both classes are registered using different decorators, lead to no registry of the models in FastOAD...

[geometry_fuselage.txt](https://github.com/fast-aircraft-design/FAST-OAD/files/6420233/geometry_fuselage.txt)
[geometry_htp_distance.txt](https://github.com/fast-aircraft-design/FAST-OAD/files/6420234/geometry_htp_distance.txt)
[__init__.txt](https://github.com/fast-aircraft-design/FAST-OAD/files/6420235/__init__.txt)

**Comment by christophe-david** [comment]
OK. Your case is not runnable outside your project, but I could make it runnable in a standalone way, and reproduce the bug.

Here is the runnable case we will work on:
[bug_import_in_init.zip](https://github.com/fast-aircraft-design/FAST-OAD/files/6432963/bug_import_in_init.zip)

For the records, the problem does not happen if your modules are part of a FAST-OAD plugin ([doc](https://fast-oad.readthedocs.io/en/latest/documentation/custom_modules/add_plugin.html) is here).
I realize we do not use the exact same mechanism for exploring plugins or exploring declared module folders (but maybe we have a fix ready there).

To be clear, I do not say you have to use the plugin mechanism. We will fix this bug anyway.
But if you want a workaround, you have one, with the additional benefit that you won't have anymore to specify your module folder in the configuration file.
