### ISSUE TITLE
Problem using new Anaconda install environment with FAST-OAD 

### ISSUE THREAD

**Issue by areysset** [fast-aircraft-design/FAST-OAD#326]
The ruamel package name is not consistent with the import from fast-oad (fastoad\io\configuration\configuration.py) with the newer version of the Anaconda environment (for those using FAST-OAD Notebooks in the Anaconda environment) !

What are the advice for beginner users? Modify line 28 of configuration.py or uninstall/reinstall ruamel with which command line?

**Comment by christophe-david** [comment]
Please see #306. Problem is from Anaconda, that does not use the official ruamel.yaml package. Taking that into account, we released FAST-OAD 1.0.2 that worked for at least some users. If you still have problems, the workaround will be to use a virtual environment, where this clone of ruamel.yaml won't be present.

You may also contribute to the [Anaconda bug report](https://github.com/conda/conda/issues/10178). That could hopefully encourage them to fix this problem.

Also, please note we will never advise to modify any file from FAST-OAD package, unless you want to do your own fork, or to contribute to FAST-OAD.
Once you use a modified copy of FAST-OAD, you cannot expect us to provide support on a version we do not provide.

But if you are willing to try and modify the calls to ruamel.yaml so they can be compliant with Anaconda's faulty install while keeping compliance with correct installations of ruamel.yaml, please feel free to propose a pull request.
