### ISSUE TITLE
Defining input variables within .xml file as a vector and inheriting shape in the models (shape_by_conn) is not working.

### ISSUE THREAD

**Issue by areysset** [fast-aircraft-design/FAST-OAD#355]
**Describe the bug**
When we try to use input parameters array of values in the .xml file and inherit in the model the shape of the array, we obtain a message error laucnhing the whole oad process.

**To Reproduce**
1. Dowload FASTGA (https://github.com/supaero-aircraft-design/FAST-GA main branch)
2. Revert comment in the file models\aerodynamics\components\compute_propeller_aero.py to inherit shape:
![image](https://user-images.githubusercontent.com/46439339/122398363-1928dc00-cf7a-11eb-9cfe-e03fbd5e1dfa.png)
3. Launch OAD process from integration_tests\oad_process\test_oad_process.py
4. Error:
[error_shape_on_con.pdf](https://github.com/fast-aircraft-design/FAST-OAD/files/6670231/error_shape_on_con.pdf)

**Expected behavior**
We expect the problem to work with shape inheritence.

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version (see pyproject.toml): FASTOAD 1.0.4

**Environment**
- Operating System: Windows 10
- Python environment: Python 3.7.1 + environment defined by pyproject.toml
- Packages: defined by pyproject.toml

**Additional context**
We wanted to inherit input shape to define propeller shape using arrays, but we will also have arrays to define the propulsion architecture (multiple propellers with different diameters...etc.)

**Comment by christophe-david** [comment]
Replaced by #357.
