### ISSUE TITLE
Setting the taxi_out phase speed

### ISSUE THREAD

**Issue by florentLutz** [fast-aircraft-design/FAST-OAD#400]
**Is your feature request related to a problem? Please describe.**
When using the mission builder and as per the documentation a taxi out phase is always conducted but the speed is by default set to 0. This can lead to issues when using propulsion model which are not valid at very low speeds in addition to which in the output file, the taxi out distance is equal to 0

**Describe the solution you'd like**
The same way the taxi in phase can be described in the mission file, we could define the settings we want for the taxi out and if nothing is specified, the current way of doing it could be used

**Describe alternatives you've considered**
An alternative for models that can't compute fuel consumption at love speed would be to have a taxi out ersatz with the desired parameters. This way the total fuel consumed would include a taxi out phase  for which the fuel consumed is not equal to zero

**Additional context**
About the alternative :
![image](https://user-images.githubusercontent.com/66668699/141121040-7d303898-500d-4485-871e-2c3df4b855a8.png)

About the proposed solution :
![image](https://user-images.githubusercontent.com/66668699/141121250-5adb3a91-88f5-490b-b291-865091b78967.png)

**Comment by christophe-david** [comment]
Since PR #430, taxi-out phase has to be defined in mission definition file. Therefore, the `true_airspeed `parameter is available for it.
