### ISSUE TITLE
Relevance of global import in submodules

### ISSUE THREAD

**Issue by esnguyenvan** [fast-aircraft-design/FAST-OAD#410]
For example in the component [compute VT](https://github.com/fast-aircraft-design/FAST-OAD/blob/master/src/fastoad/models/geometry/geom_components/vt/compute_vertical_tail.py) :

```
import openmdao.api as om

import fastoad.api as oad
from fastoad.models.geometry.geom_components.vt.components import ComputeVTChords
from fastoad.models.geometry.geom_components.vt.components import ComputeVTClalpha
from fastoad.models.geometry.geom_components.vt.components import ComputeVTDistance
from fastoad.models.geometry.geom_components.vt.components import ComputeVTMAC
from fastoad.models.geometry.geom_components.vt.components import ComputeVTSweep
from fastoad.module_management.service_registry import RegisterSubmodel
from ...constants import SERVICE_FUSELAGE_CNBETA, SERVICE_VERTICAL_TAIL_GEOMETRY

```

What are the reasons for using global imports while the lower modules [ComputeVTChords](https://github.com/fast-aircraft-design/FAST-OAD/blob/master/src/fastoad/models/geometry/geom_components/vt/components/compute_vt_chords.py), etc... are readily available through a relative import?

I imagine a case where someone would like to register a new VT module. Personally, I would start by copying the whole '[vt](https://github.com/fast-aircraft-design/FAST-OAD/tree/master/src/fastoad/models/geometry/geom_components/vt)' folder and register it as a new submodule. I would then modify the lower modules ComputeVTChords, etc... and finally I will have to change from global imports to relative imports for the changes to actually take place. This last step may a be source of confusion if ones expects from a custom module to strictly use the submodules it contains.

**Comment by christophe-david** [comment]
Agreed. Relative imports are the right thing to do here. 

Same applies for wing and horizontal tail.

**Comment by christophe-david** [comment]
Actually, I realize that incoming changes in code organisation should make this change unavoidable anyway, so don't bother too much with that.

**Comment by christophe-david** [comment]
Models have been moved to FAST-OAD_CS25 repo, and imports have been modified BTW.
