### ISSUE TITLE
Submodels registration on bottom level components

### ISSUE THREAD

**Issue by florentLutz** [fast-aircraft-design/FAST-OAD#415]
**Is your feature request related to a problem? Please describe.**
Some of the bottom level models implemented in FAST-OAD use technology dependent constant that can't be changed, which may lead to erroneous results. For instance, the computation of the aerodynamic thickness-to-chord ratio on the Boeing 757 will give a result of 0.1, while in reality it should be around 0.135. This in turns might impact the wing sizing leading to convergence on wrong values.
Those model however can be very useful when the properties of the aircraft are not known a priori so changing them is not a viable solution either.
This could be solved by the use of submodels, so that particular computation can be "switched off". However, submodels are not fully used all the way down to the bottom level models.

**Describe the solution you'd like**
Using the submodels to register the basic components in FAST-OAD when physically relevant. To reuse the example of the wing ToC if this was registered as a submodel it could be turned off so that it then becomes a user input. 

**Describe alternatives you've considered**
An alternative solution would be to put tuning factors on every models though it could be less user- and developer-friendly. Also, for that particular submodels, the factor that correspond to technology levels couls also be an input

**Comment by christophe-david** [comment]
Transferred to FAST-OAD_CS25
