### ISSUE TITLE
No reset of active_submodel when pytest are run at the same time

### ISSUE THREAD

**Issue by florentLutz** [fast-aircraft-design/FAST-OAD#440]
**Describe the bug**
Running two OAD processes in two pytests in the same pytest file will not reset to the default submodels from one process to another. In the small code provided in next step, running both pytests at the same time (e.g. running pytest submodel_bug/test_submodel.py
) will provide an error because in the second pytest the default submodel is not used, it is put to null as is the case in the first test. When running both tests separetely however, there is non error

**To Reproduce**
See little code attached : 
[submodel_bug.zip](https://github.com/fast-aircraft-design/FAST-OAD/files/8764007/submodel_bug.zip)

**Expected behavior**
Expected behaviour of when tests are run one right after the other is the behaviour when both tests are run separately

**Environment**
- Operating System: Windows 10 Entreprise
- Python environment: Python 3.9.11
- Packages:
aenum==3.1.8
anyio==3.5.0
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
asttokens==2.0.5
atomicwrites==1.4.0
attrs==21.4.0
Babel==2.9.1
backcall==0.2.0
beautifulsoup4==4.10.0
black==22.3.0
bleach==4.1.0
certifi==2021.10.8
cffi==1.15.0
charset-normalizer==2.0.12
click==8.1.2
colorama==0.4.4
debugpy==1.6.0
decorator==5.1.1
defusedxml==0.7.1
Deprecated==1.2.13
ensure==1.0.2
entrypoints==0.4
executing==0.8.3
fast-oad-core==1.3.3
fastjsonschema==2.15.3
idna==3.3
importlib-metadata==4.11.3
iniconfig==1.1.1
iPOPO==1.0.1
ipykernel==6.12.1
ipysheet==0.5.0
ipython==8.2.0
ipython-genutils==0.2.0
ipywidgets==7.7.0
jedi==0.18.1
Jinja2==3.1.1
json5==0.9.6
jsonrpclib-pelix==0.4.3.2
jsonschema==4.4.0
jupyter-client==7.2.1
jupyter-core==4.9.2
jupyter-server==1.16.0
jupyterlab==3.3.2
jupyterlab-pygments==0.1.2
jupyterlab-server==2.12.0
jupyterlab-widgets==1.1.0
lxml==4.8.0
MarkupSafe==2.1.1
matplotlib-inline==0.1.3
mistune==0.8.4
mypy-extensions==0.4.3
nbclassic==0.3.7
nbclient==0.5.13
nbconvert==6.4.5
nbformat==5.3.0
nest-asyncio==1.5.5
networkx==2.7.1
notebook==6.4.10
notebook-shim==0.1.0
numpy==1.22.3
openmdao==3.16.0
openmdao-extensions==1.0.2
packaging==21.3
pandas==1.4.2
pandocfilters==1.5.0
parso==0.8.3
pathspec==0.9.0
pickleshare==0.7.5
pip==21.2.4
platformdirs==2.5.1
plotly==5.6.0
pluggy==1.0.0
prometheus-client==0.13.1
prompt-toolkit==3.0.29
psutil==5.9.0
pure-eval==0.2.2
py==1.11.0
pycparser==2.21
pyDOE2==1.3.0
Pygments==2.11.2
pyparsing==3.0.7
pyrsistent==0.18.1
pytest==7.1.1
python-dateutil==2.8.2
pytz==2022.1
pywin32==303
pywinpty==2.0.5
pyzmq==22.3.0
requests==2.27.1
ruamel.yaml==0.17.21
ruamel.yaml.clib==0.2.6
scipy==1.8.0
Send2Trash==1.8.0
setuptools==58.0.4
six==1.16.0
sniffio==1.2.0
soupsieve==2.3.1
stack-data==0.2.0
stdatm==0.2.0
tabulate==0.8.9
tenacity==8.0.1
terminado==0.13.3
testpath==0.6.0
tomli==2.0.1
tomlkit==0.10.1
tornado==6.1
traitlets==5.1.1
typing_extensions==4.1.1
urllib3==1.26.9
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.3.2
wheel==0.37.1
widgetsnbextension==3.6.0
wincertstore==0.2
wop==1.21.3
wrapt==1.14.0
xdsmjs==1.0.1
zipp==3.8.0

**Comment by christophe-david** [comment]
Closed by #444
