### ISSUE TITLE
Introduce a method to get a variable value converted in a given input

### ISSUE THREAD

**Issue by enricostragiotti** [fast-aircraft-design/FAST-OAD#565]
**Is your feature request related to a problem? Please describe.**
There is no direct control on the unit of a VariableIO.

**Describe the solution you'd like**
It would be useful to have a method of VariableIO like "get_value_with_units(out_units)" in which the numerical value of the variable is converted in out_units.

**Comment by christophe-david** [comment]
Fixed by #570
