### ISSUE TITLE
N2 diagram

### ISSUE THREAD

**Issue by joeljezegou** [fast-aircraft-design/FAST-OAD#96]
1/ Affichage partiel quand on sélectionne un cellule. La partie droite du diragramme ne s'affiche pas. En faisant "retour", on ne retrouve pas l'image initiale. OS = Windows / Firefox
2/ Possibilité 'améliorer la lisibilité du diagramme ?
3/ Utilité d'afficher le diagramme ? Les pratiquants OAD réguliers en ont-ils besoin ?

**Comment by ScottDelbecq** [comment]
Le N2 d'OpenMDAO a bien évolué depuis, je close.
